import type {Metadata} from 'next';
import React from 'react';
import {Open_Sans} from 'next/font/google';
import '@/styles/globals.scss';

const openSans = Open_Sans({
          subsets: ['vietnamese'],
          weight: ['300', '400', '500', '600', '700', '800'],
          style: ['normal', 'italic'],
          variable: '--font-open-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
